call "debug/LBSNAnalysis.exe" foursquare 10
call "debug/LBSNAnalysis.exe" foursquare 50
call "debug/LBSNAnalysis.exe" foursquare 100
call "debug/LBSNAnalysis.exe" Gowalla 10
call "debug/LBSNAnalysis.exe" Gowalla 50
call "debug/LBSNAnalysis.exe" Gowalla 100
call "debug/LBSNAnalysis.exe" BrightKi 10
call "debug/LBSNAnalysis.exe" BrightKi 50
call "debug/LBSNAnalysis.exe" BrightKi 100