call "debug/LBSNAnalysis.exe" foursquare 10
call "debug/LBSNAnalysis.exe" BrightKi 10
call "debug/LBSNAnalysis.exe" Gowalla 10
call "debug/LBSNAnalysis.exe" foursquare 20
call "debug/LBSNAnalysis.exe" BrightKi 20
call "debug/LBSNAnalysis.exe" Gowalla 20
call "debug/LBSNAnalysis.exe" foursquare 50
call "debug/LBSNAnalysis.exe" BrightKi 50
call "debug/LBSNAnalysis.exe" Gowalla 50